import AppKit

/// macOS has no clipboard-changed notification, so the only option is polling
/// `NSPasteboard.changeCount`.
final class ClipboardWatcher {
    private var timer: Timer?
    private var lastChangeCount: Int
    private let onNewText: (String) -> Void

    /// `ConcealedType` is the convention password managers use to opt out of clipboard
    /// history — honouring it is what keeps credentials out of history.json.
    private static let ignoredTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    init(onNewText: @escaping (String) -> Void) {
        self.onNewText = onNewText
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        let timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
        timer.tolerance = 0.15  // lets the OS coalesce our wakeups
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []
        guard !types.contains(where: { Self.ignoredTypes.contains($0) }) else { return }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        onNewText(text)
    }
}
